#!/usr/bin/env bash

##
## Dependency locations
##
BOSH_LITE_REPO=${BOSH_LITE_REPO:-https://github.com/cloudfoundry/bosh-lite.git}
CF_RELEASE_VERSION=${CF_RELEASE_VERSION:-v154}
CF_RELEASE_TGZ=${CF_RELEASE_TGZ:-https://github.com/cloudfoundry/cf-release/archive/$CF_RELEASE_VERSION.tar.gz}

WORKSPACE_DIR=${WORKSPACE_DIR:-$HOME/bosh-lite-turorial}

##
## Verify local requirements
##
if [[ "${SKIP_VERIFY}X" == "X" ]]; then
    set +e

    echo Required dependencies: ruby 1.9.3+, vagrant 1.4+, git 1.7+, wget.
    echo

    ruby_installed=$(which ruby)
    ruby -v

    echo
    vagrant_installed=$(which vagrant)
    vagrant -v

    echo
    git_installed=$(which git)
    git --version

    echo
    wget_installed=$(which wget)
    wget --version | head -n1

    echo
    if [[ "${ruby_installed}X" == "X" || "${vagrant_installed}X" == "X" || "${git_installed}X" == "X" || "${wget_installed}" == "X" ]]; then
        echo Please install the missing dependencies above.
        exit 1
    fi
    set -e
    echo Press [ENTER] if your versions are ok, else Ctrl-C to cancel and manually install them.
    read

    ##
    ## Workspace setup
    ##

    echo Will use $WORKSPACE_DIR for this demo. Press [ENTER] or re-run with \$WORKSPACE_DIR set.
    read
fi

mkdir -p $WORKSPACE_DIR
cd $WORKSPACE_DIR

if [[ ! -d bosh-lite ]]; then
    git clone $BOSH_LITE_REPO bosh-lite
fi

